setwd("~/Langara/Sem 3/DANA-4820/project")

df <- read.csv('bank_data.csv')

df$y <- as.factor(df$y)
df$marital <- as.factor(df$marital)
df$default <- as.factor(df$default)
df$housing <- as.factor(df$housing)
df$loan <- as.factor(df$loan)
df$poutcome <- as.factor(df$poutcome)
df$education <- as.factor(df$education)
df$job <- as.factor(df$job)
df$month <- as.factor(df$month)

library(ggplot2)

interaction.plot(df$marital,df$education,df$y, fixed = TRUE)

interaction.plot(x.factor = df$month, trace.factor = df$marital, response = data$y,fun = mean,ylab = "month",xlab = "marital",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$month,trace.factor = df$housing,response = data$y,fun = mean,ylab = "month",xlab = "housing",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$month,trace.factor = df$loan,response = data$y,fun = mean,ylab = "month",xlab = "loan",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$month,trace.factor = df$poutcome,response = data$y,fun = mean,ylab = "month",xlab = "poutcome",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$month,trace.factor = df$education,response = data$y,fun = mean,ylab = "month",xlab = "education",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$month,trace.factor = df$job,response = data$y,fun = mean,ylab = "month",xlab = "job",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$month,trace.factor = df$day,response = data$y,fun = mean,ylab = "month",xlab = "day",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$marital,trace.factor = df$housing,response = data$y,fun = mean,ylab = "marital",xlab = "housing",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$marital,trace.factor = df$loan,response = data$y,fun = mean,ylab = "marital",xlab = "loan",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$marital,trace.factor = df$poutcome,response = data$y,fun = mean,ylab = "marital",xlab = "poutcome",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$marital,trace.factor = df$education,response = data$y,fun = mean,ylab = "marital",xlab = "education",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$marital,trace.factor = df$job,response = data$y,fun = mean,ylab = "marital",xlab = "job",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$marital,trace.factor = df$day,response = data$y,fun = mean,ylab = "marital",xlab = "day",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$housing,trace.factor = df$loan,response = data$y,fun = mean,ylab = "housing",xlab = "loan",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$housing,trace.factor = df$poutcome,response = data$y,fun = mean,ylab = "housing",xlab = "poutcome",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$housing,trace.factor = df$education,response = data$y,fun = mean,ylab = "housing",xlab = "education",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$housing,trace.factor = df$job,response = data$y,fun = mean,ylab = "housing",xlab = "job",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$housing,trace.factor = df$day,response = data$y,fun = mean,ylab = "housing",xlab = "day",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$loan,trace.factor = df$poutcome,response = data$y,fun = mean,ylab = "loan",xlab = "poutcome",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$loan,trace.factor = df$education,response = data$y,fun = mean,ylab = "loan",xlab = "education",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$loan,trace.factor = df$job,response = data$y,fun = mean,ylab = "loan",xlab = "job",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$loan,trace.factor = df$day,response = data$y,fun = mean,ylab = "loan",xlab = "day",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$poutcome,trace.factor = df$education,response = data$y,fun = mean,ylab = "poutcome",xlab = "education",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$poutcome,trace.factor = df$job,response = data$y,fun = mean,ylab = "poutcome",xlab = "job",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$poutcome,trace.factor = df$day,response = data$y,fun = mean,ylab = "poutcome",xlab = "day",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$education,trace.factor = df$job,response = data$y,fun = mean,ylab = "education",xlab = "job",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$education,trace.factor = df$day,response = data$y,fun = mean,ylab = "education",xlab = "day",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")
interaction.plot(x.factor = df$job,trace.factor = df$day,response = data$y,fun = mean,ylab = "job",xlab = "day",col = c("pink", "blue"),lty = 1,lwd = 2,trace.label = "interactions")

